### ISSUE TITLE
Unused Service-Client Connection

### ISSUE THREAD

**Issue by amanwriter** [kashifrazzaqui/vyked#142]
If a service_client only subscribes/xsubscribes to a service, even then it creates a long-lasting connection to it, which is never used since the publishing service either uses Redis or creates a new connection to send packets. 

This unused connection can potentially be used for publish/xpublish and get rid of Vyked's dependency on Redis and save repeated 'get_subscribers' calls to the registry.

**Comment by kashifrazzaqui** [comment]
You can't get rid of redis, what if this instance dies. High availability redis is to ensure that this is not brittle.

**Comment by amanwriter** [comment]
If this instance is dead, then as it is it won't be publishing anything. If and when it comes back up, its clients will reconnect to it.

**Comment by kashifrazzaqui** [comment]
No, thats not what I mean. Ask Ankit to explain otherwise will call and explain :)

**Comment by nerandell** [comment]
Instead of getting rid of redis, we should actually get rid of ``xsubscribe`` logic from vyked registry and  stop using our own implementation. High availability redis will be much more reliable. Closing this issue.

**Comment by nerandell** [comment]
Instead of getting rid of redis, we should actually get rid of `xsubscribe` logic from vyked registry and  stop using our own implementation. High availability redis will be much more reliable. Closing this issue.
