### ISSUE TITLE
using bdist_wheel from setuptools instead of distutils for distribution.

### ISSUE THREAD

**Issue by bhanuvrat** [kashifrazzaqui/vyked#37]
`distutils` is outdated and according to https://github.com/rtfd/readthedocs.org/issues/1029#issuecomment-122815228 the problem at readthedocs (https://readthedocs.org/builds/vyked/3098727/) is happening because of it.

@nerandell 
If it works with `bdist_wheel`, I shall change the distribution method.

**Comment by nerandell** [comment]
We have moved to setuptools
