### ISSUE TITLE
redis host and port should be configurable.

### ISSUE THREAD

**Issue by bhanuvrat** [kashifrazzaqui/vyked#38]
Registry assumes it would find the `redis-server running on the same machine as itself which is fine for the development box but not for staging / production.
Lets make it configurable via command line options / config files / environment variables.

@kashifrazzaqui @nerandell 
views?

**Comment by nerandell** [comment]
Registry doesn't make such an assumption. Bus takes registry host and registry port when it hosts a service. So no such assumption is made.
