### ISSUE TITLE
add new subscription strategies

### ISSUE THREAD

**Issue by kashifrazzaqui** [kashifrazzaqui/vyked#56]
@subscribe allows ALL instances to receive the publication and it does not offer reliability guarantees

@xsubscribe allows one instance to reliably receive a publication. It has two strategies
- RANDOM (only one random instance)
- LEADER  (one fixed leader)

and is implemented by local queueing at the publisher which is only cleared on ack by subscriber

``` python
@xsubscribe(strategy=RANDOM)
def some_api():
    pass
```

**Comment by nerandell** [comment]
cdff65813879fff7b76686e01aa55cf331a9606e...f4b4e1f42dc3fd920b141d8cafb673c6f0b2dc03 fixes this.
