### ISSUE TITLE
modify service instance versioning strategy at registry

### ISSUE THREAD

**Issue by kashifrazzaqui** [kashifrazzaqui/vyked#57]
registry should provide an instance of the exact same version if available, else provide the next highest non breaking version
- should not broadcast new version availability as that will cause a denial of service because all clients will upgrade immediately, let the changes propagate naturally

remember to relax packet matching to comply with this logic at service-host and service-client

**Comment by nerandell** [comment]
Due date : 31st July

**Comment by nerandell** [comment]
292f3c6
