### ISSUE TITLE
inconsistent dictionary keys

### ISSUE THREAD

**Issue by bhanuvrat** [kashifrazzaqui/vyked#65]
Through the application the keys of the dictionary being passed around change even though they refer to the same thing.

eg  Service is defined as: 

```
Service = namedtuple('Service', ['name', 'version', 'dependencies', 'host', 'port', 'node_id', 'type'])
```

but the place where service objects are created expects a dictionary with key called 
- vendors in place of dependencies. 
- service in place of name

should they not be consistent?

**Comment by kashifrazzaqui** [comment]
yes they should be consistent, fix it.
