### ISSUE TITLE
Good to have: Support required_params for non GET request as well

### ISSUE THREAD

**Issue by pmittal1982** [kashifrazzaqui/vyked#70]
Currently Vyked supports the required_params feature only for GET requests in:

```
    services.get_decorated_fun()
```

We should extend it for POST and PUT requests as well.
1. Also the response content type is hard coded to "application/json" we should read it from Accept header from request and the fallback or default should be "application/json".
2. Use **aiohttp.web.HTTPBadRequest** rather than hard coding to 400. (although not much value add.)

**Comment by nerandell** [comment]
This has been fixed while refactoring.
