### ISSUE TITLE
Services do not re-subscribe after re-registration

### ISSUE THREAD

**Issue by amanwriter** [kashifrazzaqui/vyked#89]
When the registry goes down and comes up again, services re-register, but do not re-subscribe which results in incorrect behavior for services which 'xsubscribe', as the registry returns an incorrect response for the 'get_subscribers' requests.

Note: The re-registration is handled by the registry-client, while the subscription is handled in host.py

**Comment by nerandell** [comment]
https://github.com/kashifrazzaqui/vyked/commit/f90c33252615f086da336d6d04c5a4ba950da382 fixes this.
